#ifndef _HLMSTERRAPREREQUISITES_H_
#define _HLMSTERRAPREREQUISITES_H_

enum TerrainTextureTypes {
	TERRAIN_DIFFUSE,
	TERRAIN_DETAIL_WEIGHT,
	TERRAIN_DETAIL0,
	TERRAIN_DETAIL1,
	TERRAIN_DETAIL2,
	TERRAIN_DETAIL3,
	TERRAIN_DETAIL0_NM,
	TERRAIN_DETAIL1_NM,
	TERRAIN_DETAIL2_NM,
	TERRAIN_DETAIL3_NM,
	TERRAIN_DETAIL_ROUGHNESS0,
	TERRAIN_DETAIL_ROUGHNESS1,
	TERRAIN_DETAIL_ROUGHNESS2,
	TERRAIN_DETAIL_ROUGHNESS3,
	TERRAIN_DETAIL_METALNESS0,
	TERRAIN_DETAIL_METALNESS1,
	TERRAIN_DETAIL_METALNESS2,
	TERRAIN_DETAIL_METALNESS3,
	TERRAIN_REFLECTION,
	NUM_TERRAIN_TEXTURE_TYPES
};

class HlmsTerrain;

#endif // _HLMSTERRAPREREQUISITES_H_
